#!/bin/sh

powerline_dir="$(find /usr/lib/python* -type d -path "*/site-packages/powerline/config_files" 2>/dev/null)/"
echo "moving configs to $powerline_dir"


sudo cp -rv ./colorschemes $powerline_dir
sudo cp -rv ./colors.json  $powerline_dir
sudo cp -rv ./config.json  $powerline_dir
